cases:
    test_functional_wala_lifecycle.py:LifeCycleTest.test_create_vm_password
    test_functional_wala_lifecycle.py:LifeCycleTest.test_create_vm_all
    test_functional_wala_lifecycle.py:LifeCycleTest.test_create_vm_sshkey
    test_functional_wala_general.py:GeneralTest.test_check_waagent_log
    test_functional_wala_general.py:GeneralTest.test_check_hostname
    test_functional_wala_general.py:GeneralTest.test_check_waagent_service
    test_functional_wala_general.py:GeneralTest.test_start_waagent_repeatedly
    test_functional_wala_general.py:GeneralTest.test_verify_autoupdate_enabled
    test_functional_wala_general.py:GeneralTest.test_logrotate
    test_functional_wala_general.py:GeneralTest.test_check_shadow_permission
    test_functional_wala_general.py:GeneralTest.test_check_sshdconfig_permission
    test_functional_wala_general.py:GeneralTest.test_check_swapfile_permission
    test_functional_wala_general.py:GeneralTest.test_check_selinux_status
    test_functional_wala_general.py:GeneralTest.test_event_clean_up_when_above1000
    test_functional_wala_general.py:GeneralTest.test_cleanup_runexthandlers_pid
    test_functional_wala_general.py:GeneralTest.test_not_cause_python_ftbfs
    test_functional_wala_general.py:GeneralTest.test_check_mountpoint
    test_functional_wala_general.py:GeneralTest.test_check_DATALOSS_WARNING_README
    test_functional_wala_general.py:GeneralTest.test_provision_gen2_vm
    test_functional_wala_general.py:GeneralTest.test_install_uninstall_package
    test_functional_wala_general.py:GeneralTest.test_upgrade_downgrade_package
    test_functional_wala_general.py:GeneralTest.test_provision_with_2_keys
    test_functional_wala_general.py:GeneralTest.test_host_plugin_autoupdate
    test_functional_wala_general.py:GeneralTest.test_host_plugin_extension
    test_functional_wala_general.py:GeneralTest.test_host_plugin_blob_status_upload
    test_functional_wala_general.py:GeneralTest.test_host_plugin_ignore_proxy
    test_functional_wala_general.py:GeneralTest.test_verify_no_waagent_extn_logrotate
    test_functional_wala_general.py:GeneralTest.test_verify_nic_down_up_in_one_line
    test_functional_wala_general.py:GeneralTest.test_verify_agent_cgroup_enabled
    test_functional_wala_general.py:GeneralTest.test_wala_version_not_lower_than_old_rhel
    test_functional_wala_general.py:GeneralTest.test_check_waagent_network_setup_service
    test_functional_wala_general.py:GeneralTest.test_change_python_version
    test_functional_wala_network.py:NetworkTest.test_connectivity_check
    test_functional_wala_network.py:NetworkTest.test_check_dns
    test_functional_wala_network.py:NetworkTest.test_change_hostname_check_dns
    test_functional_wala_network.py:NetworkTest.test_nmcli_change_hostname
    test_functional_wala_network.py:NetworkTest.test_kill_exthandler_change_hostname
    test_functional_wala_network.py:NetworkTest.test_change_hostname_several_times
    test_functional_wala_network.py:NetworkTest.test_provision_vm_with_multiple_nics
    test_functional_wala_network.py:NetworkTest.test_provision_vm_with_sriov_nic
    test_functional_wala_network.py:NetworkTest.test_provision_vm_with_ipv6
    test_functional_wala_network.py:NetworkTest.test_provision_vm_without_ifcfg
    test_functional_wala_network.py:NetworkTest.test_verify_dhclient_not_in_waagent_cgroup
    test_functional_wala_storage.py:StorageTest.test_verify_storage_rule_gen1
    test_functional_wala_storage.py:StorageTest.test_verify_storage_rule_gen2
    test_functional_wala_settings.py:SettingsTest.test_reset_existing_sshkey
    test_functional_wala_settings.py:SettingsTest.test_reset_existing_password
    test_functional_wala_settings.py:SettingsTest.test_reset_remote_access
    test_functional_wala_settings.py:SettingsTest.test_add_new_user
    test_functional_wala_settings.py:SettingsTest.test_run_command_shell_script
    test_functional_wala_settings.py:SettingsTest.test_run_command_ifconfig
    test_functional_wala_settings.py:SettingsTest.test_extension_uninstall
    test_functional_wala_function.py:WALAFuncTest.test_waagent_verbose
    test_functional_wala_function.py:WALAFuncTest.test_waagent_version
    test_functional_wala_function.py:WALAFuncTest.test_waagent_depro_nouser_noforce
    test_functional_wala_function.py:WALAFuncTest.test_waagent_depro_nouser_force
    test_functional_wala_function.py:WALAFuncTest.test_waagent_depro_user_noforce
    test_functional_wala_function.py:WALAFuncTest.test_waagent_depro_user_force
    test_functional_wala_function.py:WALAFuncTest.test_waagent_help
    test_functional_wala_function.py:WALAFuncTest.test_waagent_start
    test_functional_wala_function.py:WALAFuncTest.test_waagent_run_exthandlers
    test_functional_wala_function.py:WALAFuncTest.test_run_waagent_command_under_events_folder
    test_functional_wala_function.py:WALAFuncTest.test_customize_waagent_conf_path
    test_functional_wala_function.py:WALAFuncTest.test_interrupt_ctrl_c
    test_functional_wala_function.py:WALAFuncTest.test_waagent_daemon
    test_functional_wala_function.py:WALAFuncTest.test_waagent_show_configuration
    test_functional_wala_function.py:WALAFuncTest.test_waagent_collect_logs
    test_functional_wala_function.py:WALAFuncTest.test_waagent_setup_firewall
    test_functional_wala_conf.py:WALAConfTest.test_enable_verbose_logging
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_mount_point
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_file_type
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_swap_check
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_swap_unusual_check
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_mount_options
    test_functional_wala_conf.py:WALAConfTest.test_resource_disk_gpt_partition
    test_functional_wala_conf.py:WALAConfTest.test_monitor_hostname
    test_functional_wala_conf.py:WALAConfTest.test_device_timeout
    test_functional_wala_conf.py:WALAConfTest.test_http_proxy_host_port
    test_functional_wala_conf.py:WALAConfTest.test_http_proxy_system_environment
    test_functional_wala_conf.py:WALAConfTest.test_regenerate_ssh_host_key
    test_functional_wala_conf.py:WALAConfTest.test_reset_system_account
    test_functional_wala_conf.py:WALAConfTest.test_delete_root_passwd
    test_functional_wala_conf.py:WALAConfTest.test_attach_disk_check_device_timeout
    test_functional_wala_conf.py:WALAConfTest.test_autorecover_device_timeout
    test_functional_wala_conf.py:WALAConfTest.test_check_useless_parameters
    test_functional_wala_conf.py:WALAConfTest.test_self_update
    test_functional_wala_conf.py:WALAConfTest.test_extension_log_dir
    test_functional_wala_conf.py:WALAConfTest.test_customize_ssh_key_conf_path
    test_functional_wala_conf.py:WALAConfTest.test_customize_ssh_client_alive_interval
    test_functional_wala_conf.py:WALAConfTest.test_decode_execute_custom_data
    test_functional_wala_conf.py:WALAConfTest.test_ssh_host_key_pair_type
    test_functional_wala_conf.py:WALAConfTest.test_enable_disable_extension
    test_functional_wala_conf.py:WALAConfTest.test_provision_agent
    test_functional_wala_conf.py:WALAConfTest.test_enable_fips
    test_functional_wala_conf.py:WALAConfTest.test_logs_collect
    test_functional_wala_conf.py:WALAConfTest.test_enable_firewall
    test_functional_wala_conf.py:WALAConfTest.test_monitor_dhcp_client_restart_period
    test_functional_wala_conf.py:WALAConfTest.test_remove_persistent_net_rules_period
    test_functional_wala_lifecycle.py:LifeCycleTest.test_stop_vm
    test_functional_wala_lifecycle.py:LifeCycleTest.test_start_vm
    test_functional_wala_lifecycle.py:LifeCycleTest.test_restart_vm
    test_functional_wala_lifecycle.py:LifeCycleTest.test_delete_vm
    test_functional_wala_lifecycle.py:LifeCycleTest.test_create_vm_without_deprovision