cases:
    test_functional_lifecycle.py:LifeCycleTest.test_start_vm
    test_functional_lifecycle.py:LifeCycleTest.test_start_vm_iommu
    test_functional_lifecycle.py:LifeCycleTest.test_reboot_vm_from_control
    test_functional_lifecycle.py:LifeCycleTest.test_reboot_vm_inside_guest
    test_functional_lifecycle.py:LifeCycleTest.test_stop_vm
    test_functional_lifecycle.py:LifeCycleTest.test_stop_vm_inside_guest
    test_functional_lifecycle.py:LifeCycleTest.test_delete_vm
    test_functional_lifecycle.py:LifeCycleTest.test_create_snapshot_vmrunning
    test_functional_lifecycle.py:LifeCycleTest.test_create_snapshot_vmstopped
    test_functional_lifecycle.py:LifeCycleTest.test_change_instance_type
    test_functional_lifecycle.py:LifeCycleTest.test_boot_mitigations
    test_functional_lifecycle.py:LifeCycleTest.test_boot_usbcore_quirks
    test_functional_lifecycle.py:LifeCycleTest.test_boot_hpet_mmap_enabled
    test_functional_lifecycle.py:LifeCycleTest.test_boot_nr_cpus
    test_functional_lifecycle.py:LifeCycleTest.test_boot_fipsenabled
    test_functional_lifecycle.py:LifeCycleTest.test_boot_debugkernel
    test_functional_kdump.py:KdumpTest.test_kdump_no_specify_cpu
    test_functional_kdump.py:KdumpTest.test_kdump_unknown_nmi_panic_enabled
    test_functional_kdump.py:KdumpTest.test_kdump_unknown_nmi_panic_disabled
    test_functional_kdump.py:KdumpTest.test_kdump_unknown_nmi_panic_enabled_sysrq_trigger
    test_functional_kdump.py:KdumpTest.test_kdump_each_cpu
    test_functional_kdump.py:KdumpTest.test_kdump_fastboot_systemctl_kexec
    test_functional_kdump.py:KdumpTest.test_kdump_fastboot_kexec_e
    test_general_verification.py:GeneralVerification.test_check_gpgkey
    test_general_verification.py:GeneralVerification.test_check_timezone
    test_general_verification.py:GeneralVerification.test_check_virtwhat
    test_general_verification.py:GeneralVerification.test_fork_pte
    test_general_verification.py:GeneralVerification.test_xenfs_mount
    test_general_verification.py:GeneralVerification.test_xe_guest_utilities
    test_general_verification.py:GeneralVerification.test_xenfs_write_inability
    test_general_verification.py:GeneralVerification.test_check_dmesg_error
    test_general_verification.py:GeneralVerification.test_check_dmesg_fail
    test_general_verification.py:GeneralVerification.test_check_dmesg_warn
    test_general_verification.py:GeneralVerification.test_check_dmesg_calltrace
    test_general_verification.py:GeneralVerification.test_check_dmesg_unknownsymbol
    test_general_verification.py:GeneralVerification.test_check_dmesg_unable
    test_general_verification.py:GeneralVerification.test_check_journalctl_traceback
    test_general_verification.py:GeneralVerification.test_check_journalctl_dumpedcore
    test_general_verification.py:GeneralVerification.test_check_journalctl_invalid
    test_general_verification.py:GeneralVerification.test_check_journalctl_service_unknown_lvalue
    test_general_verification.py:GeneralVerification.test_check_modload
    test_general_verification.py:GeneralVerification.test_check_console_log
    test_general_verification.py:GeneralVerification.test_check_release_name
    test_general_verification.py:GeneralVerification.test_check_product_id
    test_general_verification.py:GeneralVerification.test_check_vulnerabilities
    test_general_verification.py:GeneralVerification.test_check_avclog
    test_general_verification.py:GeneralVerification.test_check_avclog_nfs
    test_general_verification.py:GeneralVerification.test_check_nouveau
    test_general_verification.py:GeneralVerification.test_check_nvme_io_timeout
    test_general_verification.py:GeneralVerification.test_check_tuned_adm_active
    test_general_verification.py:GeneralVerification.test_check_proc_self_status
    test_general_verification.py:GeneralVerification.test_check_sysfs_cpu_list
    test_general_verification.py:GeneralVerification.test_dracut_f_v
    test_general_verification.py:GeneralVerification.test_check_secure_ioerror
    test_general_verification.py:GeneralVerification.test_check_rngd
    test_general_verification.py:GeneralVerification.test_check_service
    test_general_verification.py:GeneralVerification.test_cpupower_exception
    test_general_verification.py:GeneralVerification.test_check_pkgs_list
    test_general_verification.py:GeneralVerification.test_check_firstlaunch_time
    test_general_verification.py:GeneralVerification.test_check_firstlaunch_compare
    test_general_verification.py:GeneralVerification.test_check_boot_time
    test_general_verification.py:GeneralVerification.test_check_reboot_time
    test_general_verification.py:GeneralVerification.test_check_available_clocksource
    test_general_verification.py:GeneralVerification.test_change_clocksource
    test_general_verification.py:GeneralVerification.test_change_tracer
    test_general_verification.py:GeneralVerification.test_check_tsc_deadline_timer
    test_general_verification.py:GeneralVerification.test_check_timedrift_reboot
    test_general_verification.py:GeneralVerification.test_check_timedrift_stress
    test_general_verification.py:GeneralVerification.test_check_microcode_load
    test_general_verification.py:GeneralVerification.test_check_cpu_count
    test_general_verification.py:GeneralVerification.test_check_lshw_mem
    test_general_verification.py:GeneralVerification.test_check_lspci_nvme
    test_general_verification.py:GeneralVerification.test_check_meminfo_memfree
    test_general_verification.py:GeneralVerification.test_check_rpm_V_efi
    test_general_verification.py:GeneralVerification.test_check_mem_size
    test_general_verification.py:GeneralVerification.test_check_memleaks
    test_general_verification.py:GeneralVerification.test_collect_insights_result
    test_general_verification.py:GeneralVerification.test_collect_log
    test_general_verification.py:GeneralVerification.test_subscription_manager_auto
    test_general_verification.py:GeneralVerification.test_subscription_manager_config
    test_general_verification.py:GeneralVerification.test_check_dmidecode_outofspec
    test_general_verification.py:GeneralVerification.test_podman_rm_stopped
    test_general_verification.py:GeneralVerification.test_check_systemd_analyze_verify_deprecated_unsafe
    test_general_verification.py:GeneralVerification.test_check_systemd_analyze_verify_obsolete
    test_general_verification.py:GeneralVerification.test_check_systemd_analyze_verify_ordering_cycle
    test_general_verification.py:GeneralVerification.test_podman_build_image
    test_general_verification.py:GeneralVerification.test_podman_leaks_exit
    test_general_verification.py:GeneralVerification.test_podman_dev_null_permission
    test_general_verification.py:GeneralVerification.test_check_dmidecode_dump_segfault
    test_general_verification.py:GeneralVerification.test_fips_selftest
    test_general_verification.py:GeneralVerification.test_check_cpuusage_exception
    test_general_verification.py:GeneralVerification.test_check_memusage_exception
    test_general_verification.py:GeneralVerification.test_check_dmesg_nmi
    test_general_verification.py:GeneralVerification.test_check_sys_modules_parameters
    test_general_verification.py:GeneralVerification.test_check_journalctl_denied
    test_general_verification.py:GeneralVerification.test_check_journalctl_not_found
    test_general_verification.py:GeneralVerification.test_check_journalctl_cannot
    test_general_verification.py:GeneralVerification.test_check_journalctl_unexpected
    test_functional_ltp.py:LTPRun.test_ltp_hugemmap
    test_functional_ltp.py:LTPRun.test_ltp_cpuhotplug
    test_functional_ltp.py:LTPRun.test_ltp_add_key02
    test_functional_ltp.py:LTPRun.test_ltp_quickhit
    test_functional_ltp.py:LTPRun.test_ltp_ipsec_icmp
    test_functional_network.py:NetworkTest.test_mtu_min_set
    test_functional_network.py:NetworkTest.test_iperf_ipv4
    test_functional_network.py:NetworkTest.test_sriov_ixbgevf
    test_functional_network.py:NetworkTest.test_sriov_ena
    test_functional_network.py:NetworkTest.test_sriov_ena_dmesg
    test_functional_network.py:NetworkTest.test_sriov_ena_unload_load
    test_functional_network.py:NetworkTest.test_xen_netfront_unload_load
    test_functional_network.py:NetworkTest.test_pci_reset
    test_functional_network.py:NetworkTest.test_ethtool_C_coalesce
    test_functional_network.py:NetworkTest.test_ethtool_G
    test_functional_network.py:NetworkTest.test_ethtool_K_offload
    test_functional_network.py:NetworkTest.test_ethtool_s_msglvl
    test_functional_network.py:NetworkTest.test_ethtool_X
    test_functional_network.py:NetworkTest.test_ethtool_P
    test_functional_network.py:NetworkTest.test_network_hotplug
    test_functional_network.py:NetworkTest.test_second_ip_hotplug
    test_functional_network.py:NetworkTest.test_ethtool_S_xdp
    test_functional_network.py:NetworkTest.test_persistent_route
    test_functional_storage.py:StorageTest.test_ssd_trim
    test_functional_storage.py:StorageTest.test_nvme_basic
    test_functional_storage.py:StorageTest.test_disk_info
    test_functional_storage.py:StorageTest.test_check_disk_count
    test_functional_storage.py:StorageTest.test_iostat_x
    test_functional_storage.py:StorageTest.test_multi_disk
    test_functional_storage.py:StorageTest.test_multi_disk_hotplug
    test_functional_storage.py:StorageTest.test_virsh_pci_reattach
    test_functional_storage.py:StorageTest.test_blktests_block
    test_functional_storage.py:StorageTest.test_blktests_nvme
    test_functional_storage.py:StorageTest.test_fsadm_resize
    test_functional_storage.py:StorageTest.test_fio_cpuclock
    test_functional_storage.py:StorageTest.test_fio_crctest
    test_cloud_init.py:CloudInit.test_check_username
    test_cloud_init.py:CloudInit.test_check_userdata
    test_cloud_init.py:CloudInit.test_check_config_ipv6
    test_cloud_init.py:CloudInit.test_check_output_isexist
    test_cloud_init.py:CloudInit.test_check_metadata
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_traceback
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_unexpected
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_critical
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_warn
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_error
    test_cloud_init.py:CloudInit.test_check_cloudinit_service_status
    test_cloud_init.py:CloudInit.test_check_cloudinit_log_imdsv2
    test_cloud_init.py:CloudInit.test_check_cloudinit_ds_identify_found
    test_cloud_init.py:CloudInit.test_check_lineoverwrite
    test_cloud_init.py:CloudInit.test_check_cloudinit_cfg_no_wheel
    test_cloud_init.py:CloudInit.test_check_cloudinit_fingerprints
    test_zcleanup.py:CleanUp.test_cleanupall

